### PR TITLE
Add bug report issue template

### LINKED ISSUE #107: Issue Template for Bugs
Need to implement an issue template for bugs

### PR DESCRIPTION
**Pull request by 0Grit**
Since this isn't really testable in this repository I tested it here.
https://github.com/0Grit/Testplate/issues/new/choose

<a href="https://gitpod.io/#https://github.com/golioth/zephyr-sdk/pull/113"></a>

### CODE REVIEW

**Comment by mniestroj** [comment]
There are nice templates in Zephyr: https://github.com/zephyrproject-rtos/zephyr/tree/main/.github/ISSUE_TEMPLATE.

**Comment by 0Grit** [comment]
@mniestroj you see any particular issues with the one I pulled together?
 I'll use Zephyr's for the other templates?

**Comment by 0Grit** [comment]
https://github.com/0Grit/Testplate/issues/new/choose

**Comment by vancefarren** [comment]
LGTM!

**Review by vancefarren — APPROVED** [review]

**Pull request merged**
