### PR TITLE
samples: add ethernet overlays/configs

### PR DESCRIPTION
**Pull request by alvarowolfx**
Tested with the given boards/configurations:

| Board                                                                                                           | Processor   | Network  | Description                                                |
| --------------------------------------------------------------------------------------------------------------- | ----------- | -------- | ---------------------------------------------------------- |
| [ST Nucleo F746ZG](https://docs.zephyrproject.org/2.6.0/boards/arm/nucleo_f746zg/doc/index.html)                | STM32F746ZG | Ethernet | Built in Ethernet                                          |
| [WeAct Studio Black Pill V2.0](https://docs.zephyrproject.org/2.6.0/boards/arm/blackpill_f411ce/doc/index.html) | STM32F411CE | Ethernet | Wiznet W5500 module connected over SPI                     |
| [Particle Xenon](https://docs.zephyrproject.org/2.6.0/boards/arm/particle_xenon/doc/index.html)                 | nRF52840    | Ethernet | Particle Xenon + Ethernet Featherwing                      |

The ST Nucleo F746ZG was intentionally not added to the DFU sample because by default it doesn't have partitions defined on the Device Tree.

<a href="https://gitpod.io/#https://github.com/golioth/zephyr-sdk/pull/51"></a>

### CODE REVIEW

**Comment by alvarowolfx** [comment]
Ops, just saw some tab vs space problem 😢

**Review by 0Grit — APPROVED** [review]

**Comment by mniestroj** [comment]
Two things:
- do we want to keep those boards supported as part of Zephyr SDK or rather in external repo? (will they be tested? should users treat them as with "first class support"?) @0Grit 
- can we rebase this PR on top of `main`, so that `checkpatch` and `gitlint` will show issues with commits? and then cleanup git commits accordingly to Zephyr coding style? @alvarowolfx

**Comment by 0Grit** [comment]
> Two things:
> 
> * do we want to keep those boards supported as part of Zephyr SDK or rather in external repo? (will they be tested? should users treat them as with "first class support"?) @0Grit
> * can we rebase this PR on top of `main`, so that `checkpatch` and `gitlint` will show issues with commits? and then cleanup git commits accordingly to Zephyr coding style? @alvarowolfx

Adding first class support for anything needs to be done with care while we are still testing manually.

Lets add support only for the ST dev board. @alvarowolfx thoughts?

**Comment by 0Grit** [comment]
We'd have to find a way to get the partitions defined for the ST board though. @alvarowolfx indicated they were not provided by ST and therefore DFU support is not straightforward.

Are there other ST ethernet targets that do define partitions?

**Comment by 0Grit** [comment]
@alvarowolfx Can I bother you to rebase this and then I'll take it form there?

**Comment by 0Grit** [comment]
@alvarowolfx hahaha I was just pushing him on coding style too.

**Comment by mniestroj** [comment]
@alvarowolfx 

See:
https://docs.zephyrproject.org/latest/contribute/index.html#contribution-workflow (especially "15. If reviewers do request changes to your patch, you can interactively rebase commit(s) to fix review issues. In your development repo:")
https://docs.zephyrproject.org/latest/contribute/index.html#commit-guidelines

The idea is to provide clean commit history, so that review can be done commit by commit. All the commits that fix previous commits should be squashed, as it provides no value to keep those changes separate.

**Comment by 0Grit** [comment]
Darn

**Comment by ncmiller** [comment]
Closing this due to being outdated. I will leave the branch up in case we want to migrate this to the `samples` repo.

**Pull request closed without merging**
