### PR TITLE
samples: dfu: support 'esp32' platform with sysbuild

### PR DESCRIPTION
**Pull request by mniestroj**
Add support for [sysbuild](https://docs.zephyrproject.org/latest/build/sysbuild/index.html) for `esp32` board. That way all vanilla Zephyr boards will be supported using single, much simplified build/flash flow.

### The **old** flow

Update the submodules needed by the Espressif port:
``` sh
$ git submodule update --init --recursive --checkout boot/espressif/hal/esp-idf
```

Install IDF dependencies and set environment variables:
``` sh
$ cd boot/espressif/hal/esp-idf
$ ./install.sh
$ . ./export.sh
$ cd ../..
```

Compile and generate the ELF:
``` sh
$ cmake -DCMAKE_TOOLCHAIN_FILE=tools/toolchain-<target>.cmake -DMCUBOOT_TARGET=<target> -B build -GNinja
$ cmake --build build/
```

Convert the ELF to the final bootloader image, ready to be flashed:
``` sh
$ esptool.py --chip <target> elf2image --flash_mode dio --flash_freq 40m -o build/mcuboot_<target>.bin build/mcuboot_<target>.elf
```

Flash MCUboot in your board:
``` sh
$ esptool.py -p <PORT> -b <BAUD> --before default_reset --after hard_reset --chip <target> write_flash --flash_mode dio --flash_size detect --flash_freq 40m 0x1000 build/mcuboot_<target>.bin
```

Flash Golioth DFU sample:
``` sh
$ west build -b esp32 samples/dfu
```

Sign sample image:
``` sh
$ west sign -t imgtool -- --key $(west topdir)/bootloader/mcuboot/root-rsa-2048.pem
```

Flash sample image:
``` sh
$ west flash --bin-file build/zephyr/zephyr.signed.bin --hex-file build/zephyr/zephyr.signed.hex
```

Prepare application image with new version (`1.2.3`):
``` sh
$ west sign -t imgtool --no-hex -B new.bin -- --key $(west topdir)/bootloader/mcuboot/root-rsa-2048.pem --version 1.2.3
```

### The **new** flow

Build bootloader and (signed) Golioth DFU sample:

``` sh
$ west build -b esp32 --sysbuild samples/dfu
```

Flash bootloader and sample:
``` sh
$ west flash
```

Prepare application image with new version (`1.2.3`):
``` sh
$ west build -b esp32 --sysbuild samples/dfu -- -DCONFIG_MCUBOOT_EXTRA_IMGTOOL_ARGS='"--version 1.2.3"'
```

### CODE REVIEW

**Comment by szczys** [comment]
I'm having trouble getting the second binary build to make it past the signing process. It looks like the version number is in there, but it's not used as the argument for the `--version` flag.


```
Error: Got unexpected extra argument (/home/mike/golioth-zephyr-workspace/modules/lib/golioth/build/dfu/zephyr/zephyr.signed.bin)
FATAL ERROR: command exited with status 2: /home/mike/golioth-zephyr-workspace/.venv/bin/imgtool sign --version 0.0.0+0 --align 4 --header-size 32 --slot-size 1048576 --key /home/mike/golioth-zephyr-workspace/bootloader/mcuboot/root-rsa-2048.pem 1.2.3 /home/mike/golioth-zephyr-workspace/modules/lib/golioth/build/dfu/zephyr/zephyr.bin /home/mike/golioth-zephyr-workspace/modules/lib/golioth/build/dfu/zephyr/zephyr.signed.bin
ninja: build stopped: subcommand failed.
[10/16] No configure step for 'mcuboot_espressif'
FAILED: dfu-prefix/src/dfu-stamp/dfu-build /home/mike/golioth-zephyr-workspace/modules/lib/golioth/build/dfu-prefix/src/dfu-stamp/dfu-build 
cd /home/mike/golioth-zephyr-workspace/modules/lib/golioth/build/dfu && /usr/local/bin/cmake --build .
ninja: build stopped: subcommand failed.
FATAL ERROR: command exited with status 1: /usr/local/bin/cmake --build /home/mike/golioth-zephyr-workspace/modules/lib/golioth/build

```

**Comment by mniestroj** [comment]
> I'm having trouble getting the second binary build to make it past the signing process. It looks like the version number is in there, but it's not used as the argument for the `--version` flag.
> 
> ```
> west build -b esp32 --sysbuild samples/dfu -- -DCONFIG_MCUBOOT_EXTRA_IMGTOOL_ARGS=\"1.2.3\"
> 
> ...snip...
> 
> Error: Got unexpected extra argument (/home/mike/golioth-zephyr-workspace/modules/lib/golioth/build/dfu/zephyr/zephyr.signed.bin)
> FATAL ERROR: command exited with status 2: /home/mike/golioth-zephyr-workspace/.venv/bin/imgtool sign --version 0.0.0+0 --align 4 --header-size 32 --slot-size 1048576 --key /home/mike/golioth-zephyr-workspace/bootloader/mcuboot/root-rsa-2048.pem 1.2.3 /home/mike/golioth-zephyr-workspace/modules/lib/golioth/build/dfu/zephyr/zephyr.bin /home/mike/golioth-zephyr-workspace/modules/lib/golioth/build/dfu/zephyr/zephyr.signed.bin
> ninja: build stopped: subcommand failed.
> [10/16] No configure step for 'mcuboot_espressif'
> FAILED: dfu-prefix/src/dfu-stamp/dfu-build /home/mike/golioth-zephyr-workspace/modules/lib/golioth/build/dfu-prefix/src/dfu-stamp/dfu-build 
> cd /home/mike/golioth-zephyr-workspace/modules/lib/golioth/build/dfu && /usr/local/bin/cmake --build .
> ninja: build stopped: subcommand failed.
> FATAL ERROR: command exited with status 1: /usr/local/bin/cmake --build /home/mike/golioth-zephyr-workspace/modules/lib/golioth/build
> ```

Thanks for catching this! I've updated `-DCONFIG_MCUBOOT_EXTRA_IMGTOOL_ARGS=...` argument in docs and in this PR description. It should work now.

**Comment by szczys** [comment]
That got it to build, but when I test the upgrade it reboots and restarts the download once again:

```
[00:00:57.134,000] <dbg> golioth_dfu: data_received: Received 1024 bytes at offset 637952
[00:00:57.185,000] <dbg> golioth_dfu: data_received: Received 1024 bytes at offset 638976
[00:00:57.302,000] <dbg> golioth_dfu: data_received: Received 972 bytes at offset 640000 (last)
[00:00:57.686,000] <inf> golioth_dfu: Requesting upgrade
[00:00:57.686,000] <inf> golioth_dfu: Rebooting in 1 second(s)
uart:~$ ets Jul 29 2019 12:21:46
rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fffa5b0,len:5572
load:0x40093000,len:24992
ho 0 tail 12 room 4
load:0x4009b800,len:6736
entry 0x40093414
[esp32] [INF] [boot] chip revision: 3
[esp32] [INF] Enabling RNG early entropy source...
[esp32] [INF] *** Booting MCUboot build v1.7.0-636-g1558e7a ***
[esp32] [INF] Primary image: magic=bad, swap_type=0x1, copy_done=0x2, image_ok=0x2
[esp32] [INF] Scratch: magic=unset, swap_type=0x1, copy_done=0x3, image_ok=0x3
[esp32] [INF] Boot source: none
[esp32] [INF] Swap type: test
[esp32] [ERR] Image in the secondary slot is not valid!
[esp32] [INF] Disabling RNG early entropy source...
[esp32] [INF] br_image_off = 0x10000
[esp32] [INF] ih_hdr_size = 0x20
[esp32] [INF] Loading image 0 - slot 0 from flash, area id: 1
[esp32] [INF] DRAM segment: start=0x1cd80, size=0x1fcc, vaddr=0x3ffb0000
[esp32] [INF] IRAM segment: start=0x1ed4c, size=0xaca8, vaddr=0x40080000
0x40080000: _WindowOverflow4 at /home/mike/golioth-zephyr-workspace/zephyr/arch/xtensa/core/window_vectors.S:56

[esp32] [INF] start=0x40089768
0x40089768: __start at /home/mike/golioth-zephyr-workspace/zephyr/soc/xtensa/esp32/loader.c:86


*** Booting Zephyr OS build zephyr-v3.3.0-3248-g954c4f2a564c ***
[00:00:03.370,000] <inf> golioth_system: Initializing
[00:00:03.383,000] <inf> fs_nvs: 6 Sectors of 4096 bytes
[00:00:03.383,000] <inf> fs_nvs: alloc wra: 0, f88
[00:00:03.383,000] <inf> fs_nvs: data wra: 0, 9c
[00:00:03.385,000] <dbg> golioth_dfu: main: Start DFU sample
[00:00:03.385,000] <err> golioth_dfu: Failed to confirm image: -5
[00:00:03.385,000] <inf> golioth_samples: Waiting for interface to be up
[00:00:03.385,000] <inf> golioth_samples: Connecting to WiFi
[00:00:14.086,000] <inf> net_dhcpv4: Received: 192.168.1.157
[00:00:14.086,000] <inf> golioth_wifi: Connected with status: 0
Connected
[00:00:14.087,000] <inf> golioth_wifi: Successfully connected to WiFi
[00:00:14.087,000] <inf> golioth_system: Starting connect
[00:00:14.324,000] <inf> golioth_system: Client connected!
[00:00:14.394,000] <dbg> golioth_dfu: golioth_desired_update: Desired
                                      a3 01 1a 64 4a d5 c5 02  78 40 31 37 61 31 39 37 |...dJ... x@17a197
                                      31 65 64 64 65 64 37 36  64 32 37 64 36 65 31 63 |1edded76 d27d6e1c
                                      61 33 33 38 37 38 35 63  39 32 61 38 61 39 64 30 |a338785c 92a8a9d0
                                      61 66 32 31 66 33 34 33  35 31 35 37 32 36 66 34 |af21f343 515726f4
                                      66 32 39 33 39 37 63 38  32 66 03 81 a6 01 64 6d |f29397c8 2f....dm
                                      61 69 6e 02 65 31 2e 32  2e 33 03 78 40 63 66 61 |ain.e1.2 .3.x@cfa
                                      38 30 65 33 33 65 34 38  39 65 61 63 63 36 32 34 |80e33e48 9eacc624
                                      31 39 64 38 33 32 35 61  66 35 64 31 61 31 37 65 |19d8325a f5d1a17e
                                      30 66 63 35 63 36 36 39  62 34 62 63 66 65 39 38 |0fc5c669 b4bcfe98
                                      34 32 37 66 66 31 66 30  32 35 31 35 61 04 1a 00 |427ff1f0 2515a...
                                      09 c7 cc 05 70 2f 2e 75  2f 63 2f 6d 61 69 6e 40 |....p/.u /c/main@
                                      31 2e 32 2e 33 06 67 64  65 66 61 75 6c 74       |1.2.3.gd efault
[00:00:14.394,000] <inf> golioth: Manifest sequence-number: 1682625989
[00:00:14.500,000] <dbg> golioth_dfu: data_received: Received 1024 bytes at offset 0
[00:00:14.500,000] <inf> mcuboot_util: Swap type: none
[00:00:14.500,000] <inf> golioth_dfu: swap type: none
[00:00:14.609,000] <dbg> golioth_dfu: data_received: Received 1024 bytes at offset 1024
[00:00:14.664,000] <dbg> golioth_dfu: data_received: Received 1024 bytes at offset 2048
[00:00:14.715,000] <dbg> golioth_dfu: data_received: Received 1024 bytes at offset 3072
```

**Review by szczys — APPROVED** [review]
LGTM!

**Pull request merged**
